### ISSUE TITLE
SaltXMLExporter throws PepperModuleException

### ISSUE THREAD

**Issue by sdruskat** [korpling/pepper#113]
- Ubuntu 16.04
- Pepper 3.1.1-SNAPSHOT (https://github.com/korpling/pepper/commit/0e20e6bbead899607022e9b3d497ebae91750504)

Simple Pepper workflow definition:

```
<?xml version='1.0' encoding='UTF-8'?>
<pepper-job id="some-title" version="1.0">
	<importer name="MyImporter" path="../mycorpus/"/>
	<exporter name="SaltXMLExporter" path="../sxml/">
	</exporter>
</pepper-job>
```
Result:
```
CONVERSION ENDED WITH ERRORS, REQUIRED TIME: 00:00:06.151 s
   Failed to process document by module 'ex1:SaltXMLExporter(SaltXMLExporter, 0.0)'. Nested exception was:  (PepperModuleException)
full stack trace:
org.corpus_tools.pepper.modules.exceptions.PepperModuleException: Failed to process document by module 'ex1:SaltXMLExporter(SaltXMLExporter, 0.0)'. Nested exception was: 
	at org.corpus_tools.pepper.core.PepperJobImpl.convert(PepperJobImpl.java:998)
	at org.corpus_tools.pepper.cli.PepperStarter.convert(PepperStarter.java:533)
	at org.corpus_tools.pepper.cli.PepperStarter.main(PepperStarter.java:1436)
Caused by: org.corpus_tools.salt.exceptions.SaltResourceException: Cannot store document graph to file '/home/stephan/sxml/corpus/document/doc_2.salt', because the opened stream is not closable. 
	at org.corpus_tools.salt.util.internal.persistence.SaltXML10Writer.writeDocumentGraph(SaltXML10Writer.java:354)
	at org.corpus_tools.salt.util.SaltUtil.saveDocumentGraph(SaltUtil.java:610)
	at org.corpus_tools.salt.common.impl.SDocumentImpl.saveDocumentGraph(SDocumentImpl.java:189)
	at org.corpus_tools.salt.util.SaltUtil.saveCorpusGraph(SaltUtil.java:661)
	at org.corpus_tools.salt.util.SaltUtil.saveSaltProject(SaltUtil.java:781)
	at org.corpus_tools.pepper.modules.coreModules.SaltXMLExporter.start(SaltXMLExporter.java:140)
	at org.corpus_tools.pepper.core.ModuleControllerImpl$2.run(ModuleControllerImpl.java:289)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ctc.wstx.exc.WstxIOException: Stream Closed
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:262)
	at org.corpus_tools.salt.util.internal.persistence.SaltXML10Writer.writeDocumentGraph(SaltXML10Writer.java:351)
	... 11 more
Caused by: java.io.IOException: Stream Closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at com.ctc.wstx.io.UTF8Writer.flush(UTF8Writer.java:100)
	at com.ctc.wstx.sw.BufferingXmlWriter.flush(BufferingXmlWriter.java:242)
	at com.ctc.wstx.sw.BaseStreamWriter.flush(BaseStreamWriter.java:260)
	... 12 more
```

**Comment by sdruskat** [comment]
Seems that the problem is that the `FileOutputStream` is used in a `try -with-resources` and when `finally` is hit the stream is already closed.

```java
public void writeDocumentGraph(SDocumentGraph graph) {
	XMLStreamWriter xml = null;
	try (OutputStream output = new FileOutputStream(path)) {
		xml = xmlFactory.createXMLStreamWriter(output, "UTF-8");
			xml.writeStartDocument("1.0");
		if (isPrettyPrint) {
			xml.writeCharacters("\n");
		}
			writeDocumentGraph(xml, graph);
			xml.writeEndDocument();
	} catch (XMLStreamException | IOException e) {
		throw new SaltResourceException("Cannot store document graph to file '" + getLocationStr() + "'. ", e);
	} finally {
		if (xml != null) {
			try {
				xml.flush();
				xml.close();
			} catch (XMLStreamException e) {
				throw new SaltResourceException("Cannot store document graph to file '" + getLocationStr()
						+ "', because the opened stream is not closable. ", e);
			}
		}
	}
}
```

**Comment by sdruskat** [comment]
This issue was moved to korpling/salt#126
